#pragma config(Sensor, S1,     Lcolor,         sensorEV3_Color)
#pragma config(Sensor, S4,     Rcolor,         sensorEV3_Color)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Side,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          Vertical,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "WRO_2025.h"

task main()
{
	clearTimer(T1);
	while(time1[T1] <= 690){
		/*Pid pid;
		initPid(pid, 1.6, 0.001, 1);
		pidTrace(pid,70);*/
		drive(50);
		displayBigTextLine(1, "%d", getColorReflected(Lcolor));
		displayBigTextLine(5, "%d", getColorReflected(Rcolor));
	}
}
